### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [10]:
import numpy as np
x=np.arange(1,10,dtype=float).reshape(3,3)
x[1,1]=np.nan
print('Original array:')
print(x)
print('        ')
print('Find the missing data of the said array:')
print(np.isnan(x))

Original array:
[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]
        
Find the missing data of the said array:
[[False False False]
 [False  True False]
 [False False False]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [12]:
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
print(a==b)

[ True  True  True  True  True]


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [25]:
array= np.array([[9 ,7, 1],[8, 3, 2],[9, 1, 3],[0,3, 1]]) 
print('Original array:')
print(array)
print('  ')
print('after replacing the first and last rows')
array[[0,3]]=array[[3,0]]
print(array)

Original array:
[[9 7 1]
 [8 3 2]
 [9 1 3]
 [0 3 1]]
  
after replacing the first and last rows
[[0 3 1]
 [8 3 2]
 [9 1 3]
 [9 7 1]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [28]:
list=[1,2,3,4,5]
tuple=(1,2,3,4,6)
print(np.array(list))
print(np.array(tuple))

[1 2 3 4 5]
[1 2 3 4 6]


###### 5. Write a NumPy program to find common values between two arrays.

In [42]:
x=np.array([1,7,6,9,2])
y=np.array([4,5,7,9,6])
a=''
for i in x:
    for j in y:
        if i==j:
            a=a+str(i)
print('the common values between two arrays are: ')
for i in a:
    print(i,end='  ')

the common values between two arrays are: 
7  6  9  

###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [49]:
x=np.array([1,2,3,4,5,6,7,8])
print(x)
print('  ')
y=x.reshape(2,4)          
print('(2,4)\n',y)
print('  ')
z=x.reshape(4,2) 
print('(4,2)\n',z)

[1 2 3 4 5 6 7 8]
  
(2,4)
 [[1 2 3 4]
 [5 6 7 8]]
  
(4,2)
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
### sample output

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [58]:
print('Original array:')
print(np.array([10,10,20, 10, 20 ,20, 20, 30, 30, 50, 40, 40]))
print('Frequency of unique values of the said array:')
print(np.unique(np.array([10,10,20, 10, 20 ,20, 20, 30, 30, 50, 40, 40]),return_counts=True))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
(array([10, 20, 30, 40, 50]), array([3, 4, 2, 2, 1], dtype=int64))


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [60]:
a=np.arange(3)

array([0, 1, 2])

In [61]:
b=np.arange(3).reshape((3,1))

array([[0],
       [1],
       [2]])

In [63]:
np.arange(3).reshape((3,1))+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [65]:
# example 2
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.arange(3)

array([0, 1, 2])

In [67]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [70]:
x=arra_data = np.arange(0,16).reshape((4, 4))
x[1]

array([4, 5, 6, 7])

In [ ]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [77]:
x=arra_data = np.arange(0,16).reshape((4, 4))
print(x)

print('Extracted data: Third and fourth elements of the first and second rows ')
print(x[0:2,2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [82]:
import datetime
today=datetime.datetime.today()
print('Todays Date: ',today)
yesterday=today-datetime.timedelta(days=1)
print('Yesterday: ',yesterday)
tomorrow=today+datetime.timedelta(days=1)
print('Tomorrow: ',tomorrow)

Todays Date:  2022-09-10 12:37:15.051743
Yesterday:  2022-09-09 12:37:15.051743
Tomorrow:  2022-09-11 12:37:15.051743


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [85]:
print("First Monday in May 2017:")
print(np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon'))


First Monday in May 2017:
2017-05-01


In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
