In [1]:
import numpy as np

In [29]:
#Creating  Array

In [3]:
k=np.array([1, 2, 3])  #Array with Rank 1
print(k)
print(len(k))

[1 2 3]
3


In [31]:
np.array([[1, 2, 3],[4, 5, 6]])            #Array with Rank 2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
np.array((1, 3, 2)) #Array created using tuple

array([1, 3, 2])

In [2]:
k=np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],
          [2.6, 0, 7, 8],[3, -7, 4, 2.0]],dtype=int)
print(k.shape)
print(k.size)
print(len(k))

(4, 4)
16
4


In [34]:
x=np.array(5)
x

array(5)

In [35]:
# to find ndim array

In [36]:
x.ndim

0

In [37]:
x=np.array([5])

In [38]:
x.ndim

1

In [39]:
x=np.array([[5]])
x.ndim

2

In [40]:
x=np.array([[5],[3]])
x.ndim

2

In [41]:
x=np.array([[[5],[3],[6]]])
x.ndim

3

In [42]:
# len of array

In [43]:
y=np.array([5,4,3,2,1])
len(y)

5

In [44]:
k=np.array(6,dtype=float,ndmin=4)
k

array([[[[6.]]]])

In [45]:
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [46]:
x=np.array([1,2,3.3,4,5])
x

array([1. , 2. , 3.3, 4. , 5. ])

In [47]:
x=np.array([1,2,3.3,4+2j,5])
x

array([1. +0.j, 2. +0.j, 3.3+0.j, 4. +2.j, 5. +0.j])

In [48]:
x=np.array([1,2,3.3,4+2j,5,'a'])
x

array(['1', '2', '3.3', '(4+2j)', '5', 'a'], dtype='<U64')

In [49]:
# shape

In [50]:
import numpy as np
x=np.arange(1,101) 
x.shape=1,100
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [51]:
x=np.array([1,2,3,4,5])
x.shape

(5,)

In [52]:
x=np.array([[1,2,3]])
x.shape

(1, 3)

In [53]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x.shape)
print(x.ndim)

(3, 3)
2


In [54]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(x.shape)
print(x.ndim)

(1, 3, 3)
3


In [55]:
# shape of a 3dim array will return a depth rows and columns

In [56]:
x=np.array([[[1,2,3]]])
x.shape

(1, 1, 3)

In [57]:
z=np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
z.shape

(2, 3)

In [59]:
y=np.array([[1,2,4],[3,6,4],[5,10,6]])
y.shape

(3, 3)

In [60]:
# Zero

In [61]:
np.zeros((2,3)) # 2,3 indicates the rows and colmns

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.zeros((10,),dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
# full

In [64]:
np.full((3,5),11) #3,5 tell rows and colums and 11 indicate the value to be filled by

array([[11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11]])

In [65]:
# eye -> gives the Identity Matrix(diagonal valuse be 1's)

In [66]:
np.eye(3,3) # diagonal valus becomes 1 and remaining values are zeros

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
np.eye(6,k=1)    # for upper diagonal matrix

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
np.eye(6,k=-1)  # for lower diagonal matrix

array([[0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [68]:
# type()

In [69]:
x=np.array([[[10]]])
type(x)

numpy.ndarray

In [70]:
# diag

In [71]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [72]:
np.diag([1,2,3,4,5,6,7])

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [73]:
# arange ---> gives the output in  1dim

In [74]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [75]:
np.arange(100,110)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [76]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [77]:
np.arange(1,10,4)

array([1, 5, 9])

In [78]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
# linspace -> Splits the given range of values into given linspae value and,
#gives the one dimen array including end value.

In [ ]:
# linspace(startvalue,endvalue,num,endpoint=True/False,retstep,dtype)
# num-> num used to split the range into n number of times
# endpoint=True/False used to include the endvalue or not.
# retstep= will give difference between the elements and return in a tupple. 
#detault it will be flase

In [9]:
np.linspace(0,10)  # num-> by default if you not mention num it will return you 50 vales. with including the end value.

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [12]:
np.linspace(0,10,10,endpoint=False,retstep=True)  # hear 1.0 is the retstep.

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), 1.0)

In [8]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [80]:
np.linspace(1,10,11) # 11 indicates the number of parts to split into with in the given range.

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [81]:
np.linspace(1,10,7) # 7 indicates the number of parts to split into.

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [83]:
np.linspace(1,100,10) # 1-dim array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [4]:
# rand

In [9]:
x=np.random.rand(2,3)
x

array([[0.19285681, 0.9367124 , 0.59192954],
       [0.32178494, 0.02684489, 0.51054093]])

In [7]:
x=np.random.rand(5)
x

array([0.82765727, 0.01841591, 0.55106983, 0.13039765, 0.87714886])

In [5]:
x=np.random.randn(5)
x

array([ 1.30551075,  0.16190184,  0.46979984,  1.60288256, -0.61158701])

In [4]:
x=np.random.randn(2,3)
x

array([[-0.59976623,  2.02611218, -0.95627211],
       [-0.48167074,  0.17235835,  0.10260041]])

In [84]:
# random.random

In [85]:
np.random.random((4,4))

array([[0.85520697, 0.9411633 , 0.66976822, 0.40872293],
       [0.13214575, 0.5238494 , 0.81261979, 0.60540436],
       [0.62096035, 0.81093004, 0.70049547, 0.82823529],
       [0.2775455 , 0.4434226 , 0.57990431, 0.6810408 ]])

In [86]:
x=np.random.random((4,4))
x.ndim

2

In [87]:
np.random.random((3,4)) # for 2dim array

array([[0.36207517, 0.35282481, 0.50319342, 0.25258731],
       [0.70797689, 0.81450164, 0.75466285, 0.84504533],
       [0.91347934, 0.15759385, 0.50842173, 0.28687115]])

In [88]:
np.random.random((20,)) # for 1dim array

array([0.22644861, 0.28233732, 0.88521805, 0.4743242 , 0.17281965,
       0.88965867, 0.17780711, 0.63488664, 0.64910843, 0.17195972,
       0.35416918, 0.69501056, 0.57741176, 0.12303932, 0.76398081,
       0.66805584, 0.41239419, 0.97056665, 0.62439918, 0.74787467])

In [89]:
np.random.random((5,5))

array([[0.80709923, 0.55386866, 0.35885804, 0.55566565, 0.84080341],
       [0.70617031, 0.21502206, 0.89227575, 0.21520533, 0.37260697],
       [0.33159907, 0.71731293, 0.09465979, 0.60735975, 0.03732994],
       [0.15217119, 0.10611561, 0.57981584, 0.1617158 , 0.41653337],
       [0.55405488, 0.31583233, 0.24231957, 0.10610132, 0.15799406]])

In [90]:
# Slicing

In [91]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
# Slicing Based Indexing

In [93]:
x[0:2,1:3] # Slicing Based Indexing

array([[2, 3],
       [5, 6]])

In [94]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

In [95]:
sliced_arr= arr[:2, ::2]  #Array with first 2 rows and" " alternate columns(0 and 2):
sliced_arr 

array([[-1.,  0.],
       [ 4.,  6.]])

In [96]:
 # integer based indexing

In [97]:
x1=np.arange(1,5)
print(x1)
x1[0]               # integer based indexing

[1 2 3 4]


1

In [98]:
x1[1:3]


array([2, 3])

In [99]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
x[0,0]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1

In [100]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
Index_arr = arr[[1, 1, 0, 3], 
                [3, 2, 1, 0]]   #Elements at indices (1, 3), "  "(1, 2), (0, 1), (3, 0)

In [102]:
Index_arr 

array([0., 6., 2., 3.])

In [103]:
y=x[1:,1:] # in Slicing base indexing, if you change the sub array the original array will also effected by the newvalue
y

array([[5, 6],
       [8, 9]])

In [104]:
y[0,0]=100

In [105]:
y

array([[100,   6],
       [  8,   9]])

In [106]:
x

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

In [107]:
x=np.random.random((5,5))
print('x=',x)
print('\n')
print(x[1:,1:4]) #(1:)-> Rows, (1:4)-> Columns

x= [[0.78420497 0.59016964 0.24288975 0.79829762 0.9928539 ]
 [0.17858422 0.7628937  0.11433569 0.23526719 0.46059225]
 [0.66415804 0.70499342 0.39228398 0.08392564 0.04651394]
 [0.81162857 0.94965688 0.81843381 0.59919612 0.89075665]
 [0.66597829 0.37807085 0.1922498  0.65573905 0.47023604]]


[[0.7628937  0.11433569 0.23526719]
 [0.70499342 0.39228398 0.08392564]
 [0.94965688 0.81843381 0.59919612]
 [0.37807085 0.1922498  0.65573905]]


In [108]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=x[0:2,0:2]
y

array([[1, 2],
       [4, 5]])

In [109]:
y[0,0]=10
print(x)
print('\n')
print(y)

[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


[[10  2]
 [ 4  5]]


In [110]:
#integer based indexing [[row],[cloumn]]
# properties 
# 1----- its also used to get the sub array
# 2------ we can access any element in the original array
# 3------ its will be a copy of the array (if we change sub array , there will not be any change in original array)
# 4 ----- sub array will be lower dimension array (original n dimension---- then sub array is n-1 dimension)


In [111]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
x


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [112]:
y=x[[1,1,2,2,3,3],[1,2,1,2,1,2]]
y

array([ 6,  7, 10, 11, 14, 15])

In [113]:
y[0]=100

In [114]:
y

array([100,   7,  10,  11,  14,  15])

In [115]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [116]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
x[[0,2],[0,1]]   # This is Integer based in dexing so
#0,0 is 1 and 2,1 is 8 hear 2nd row 1st column value is 8

array([1, 8])

In [118]:
# how to apply math operation on array 


In [119]:
# To do the mathematical operations like +,-,*,/,//,** both the arrary lenth shoud be equal
x=np.array([1,2,3,4,5]) # 1dim
y=np.array([5,4,3,2,1]) # 1dim
print(x+y)
print(x-y)
print(x*y)
print(x/y)
print(x**y)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]
[0.2 0.5 1.  2.  5. ]
[ 1 16 27 16  5]


In [120]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[4, 3],[2, 1]])
print("Adding 1 to every element:", a + 1)
print ("\nSubtracting 2 from each element:", b - 2)
# sum of array elements
print ("\nSum of all array elements: ", a.sum())
# Adding two arrays
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


In [121]:
arr1 = np.array([[4, 7], [2, 6]],dtype = np.float64)
arr2 = np.array([[3, 6], [2, 8]],dtype = np.float64) 
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ")
print(Sum)

Addition of Two Arrays: 
[[ 7. 13.]
 [ 4. 14.]]


In [122]:
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ")
print(Sum1)


Addition of Array elements: 
19.0


In [123]:
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ")
print(Sqrt)
 


Square root of Array1 elements: 
[[2.         2.64575131]
 [1.41421356 2.44948974]]


In [125]:
print(x<y)


[ True  True False False False]


In [126]:
x>y

array([False, False, False,  True,  True])

In [127]:
z=x==y
z

array([False, False,  True, False, False])

In [128]:
x!=y

array([ True,  True, False,  True,  True])

In [129]:
x<=y

array([ True,  True,  True, False, False])

In [130]:
x>=y

array([False, False,  True,  True,  True])

In [131]:
x1=np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2dim array
y1=np.array([[5,4,3,2,1],[10,9,8,7,6]]) # 2dim array
x1+y1

array([[ 6,  6,  6,  6,  6],
       [16, 16, 16, 16, 16]])

In [132]:
print(x1<y1) # returns a Boolean datatype in the same ndim array size

[[ True  True False False False]
 [ True  True False False False]]


In [133]:
# Reshape The numpy.reshape() function shapes an array without changing the data of the array.

In [134]:
import numpy as np
x=np.arange(8)
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [135]:
x.reshape(4,2) # reshape size should be equal to the no.of elements in the array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [136]:
x.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [137]:
x=np.arange(1,51).reshape(10,5)


In [138]:
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [139]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
x.shape

(2, 3)

In [141]:
x.reshape(6,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [142]:
import numpy as np
x=np.arange(1,101)
x.shape=1,100


In [143]:
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
         27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
         40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
         66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
         79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
         92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [144]:
# boolean based indexing

In [145]:
x=np.array([[2,3,4],[5,6,7]])
x

array([[2, 3, 4],
       [5, 6, 7]])

In [146]:
y=np.array([[12,3,4],[15,6,7]])
y

array([[12,  3,  4],
       [15,  6,  7]])

In [147]:
x==y

array([[False,  True,  True],
       [False,  True,  True]])

In [148]:
# boolean based indexing -- to get an element which satisfies the condition

In [149]:
x=np.arange(1,101).reshape(10,10)
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [150]:
#masking

In [151]:
x%5==0

array([[False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False, False, False, False,  True, False, False, False, False,
         True]])

In [152]:
x[x%5==0] # Prints only the true values

array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100])

In [153]:
y=x[(x%5==0) | (x%3==0)]
y

array([  3,   5,   6,   9,  10,  12,  15,  18,  20,  21,  24,  25,  27,
        30,  33,  35,  36,  39,  40,  42,  45,  48,  50,  51,  54,  55,
        57,  60,  63,  65,  66,  69,  70,  72,  75,  78,  80,  81,  84,
        85,  87,  90,  93,  95,  96,  99, 100])

In [154]:
y[0]=1000
y


array([1000,    5,    6,    9,   10,   12,   15,   18,   20,   21,   24,
         25,   27,   30,   33,   35,   36,   39,   40,   42,   45,   48,
         50,   51,   54,   55,   57,   60,   63,   65,   66,   69,   70,
         72,   75,   78,   80,   81,   84,   85,   87,   90,   93,   95,
         96,   99,  100])

In [155]:
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [156]:
# Dot Product 
# Condition =A(m,n) B(m,n)condition A(n)==B(m) and gives a array of m*n

In [157]:
x=np.arange(1,7)
x

array([1, 2, 3, 4, 5, 6])

In [158]:
x.shape

(6,)

In [159]:
x=x.reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [160]:
y=np.arange(1,10).reshape(3,3)
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
z=np.dot(x,y) 
z

array([[30, 36, 42],
       [66, 81, 96]])

In [162]:
z.shape

(2, 3)

In [163]:
# Some additional Functions

In [164]:
x=np.array([1,2,3])
y=np.array([5,6,7])
np.add(x,y)

array([ 6,  8, 10])

In [165]:
np.subtract(x,y)

array([-4, -4, -4])

In [166]:
np.multiply(x,y)

array([ 5, 12, 21])

In [167]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081])

In [168]:
# inf Infinite value

In [169]:
x=np.arange(1,10,dtype=float).reshape(3,3)
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [170]:
x[0,1]=np.inf
x

array([[ 1., inf,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [171]:
# nan -> Not a number  (missing value)

In [172]:
x[2,1]=np.nan
x

array([[ 1., inf,  3.],
       [ 4.,  5.,  6.],
       [ 7., nan,  9.]])

In [173]:
x=np.arange(1,10,dtype=float).reshape(3,3)
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [174]:
x[0,1]=np.inf
x

array([[ 1., inf,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [175]:
x[1,1]=np.nan
x

array([[ 1., inf,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [176]:
#isinf

In [177]:
np.isinf(x)

array([[False,  True, False],
       [False, False, False],
       [False, False, False]])

In [178]:
#isnan

In [179]:
np.isnan(x)

array([[False, False, False],
       [False,  True, False],
       [False, False, False]])

In [180]:
z=np.arange(1,31,dtype=float).reshape(5,6)
z

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.]])

In [181]:
z[z%2!=0]=np.inf
z

array([[inf,  2., inf,  4., inf,  6.],
       [inf,  8., inf, 10., inf, 12.],
       [inf, 14., inf, 16., inf, 18.],
       [inf, 20., inf, 22., inf, 24.],
       [inf, 26., inf, 28., inf, 30.]])

In [182]:
z[z%2==0]=np.nan
z

C:\Users\Gogula Vinay\AppData\Local\Temp\ipykernel_12628\1203910585.py:1: RuntimeWarning: invalid value encountered in remainder
  z[z%2==0]=np.nan


array([[inf, nan, inf, nan, inf, nan],
       [inf, nan, inf, nan, inf, nan],
       [inf, nan, inf, nan, inf, nan],
       [inf, nan, inf, nan, inf, nan],
       [inf, nan, inf, nan, inf, nan]])

In [183]:
np.isnan(z)

array([[False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True]])

In [184]:
z[np.isnan(z)]


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan])

In [185]:
z[np.isnan(z)].shape

(15,)

In [186]:
print(len(z[np.isnan(z)]))
print(z[np.isnan(z)].shape)

15
(15,)


In [ ]:
# 17 Aug 2022

In [ ]:
# sum -> gives the sum of array

In [11]:
x=np.random.randint(10,21,(3,4))
x

array([[15, 10, 17, 10],
       [11, 11, 18, 11],
       [12, 11, 11, 20]])

In [12]:
x.sum()

157

In [13]:
x.sum(axis=1)

array([52, 51, 54])

In [16]:
import numpy as np
x=np.array((1,2,3,4))
x

array([1, 2, 3, 4])

In [15]:
np.sum(x)

10

In [3]:
# Prod -> Gives the product of the whole matrix

In [4]:
np.prod(x)

24

In [5]:
x=np.arange(1,10).reshape(3,3)

In [6]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.prod(x)

362880

In [8]:
np.prod(x,axis=0)

array([ 28,  80, 162])

In [9]:
np.prod(x,axis=1)

array([  6, 120, 504])

In [10]:
x=np.arange(1,10,dtype=float).reshape(3,3)
x

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
x[1,1]=np.nan

In [17]:
np.prod(x)

nan

In [ ]:
# nanprod converts nan into 1

In [18]:
np.nanprod(x)

72576.0

In [21]:
np.nanprod(x,axis=0)

array([ 28.,  16., 162.])

In [22]:
np.nanprod(x,axis=1)

array([  6.,  24., 504.])

In [19]:
np.sum(x)

nan

In [ ]:
# nansum converts nan into 0

In [20]:
np.nansum(x)

40.0

In [23]:
np.nansum(x,axis=0)

array([12., 10., 18.])

In [24]:
np.nansum(x,axis=1)

array([ 6., 10., 24.])

In [28]:
x=np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# cumulative sum (cumsum())

In [29]:
np.cumsum(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [ ]:
# cumulative product (cumprod())

In [39]:
np.cumprod(x)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [32]:
x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
np.cumsum(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [34]:
np.cumsum(x,axis=0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [35]:
np.cumsum(x,axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15],
       [ 7, 15, 24]], dtype=int32)

In [36]:
np.cumprod(x)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [37]:
np.cumprod(x,axis=0)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]], dtype=int32)

In [38]:
np.cumprod(x,axis=1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]], dtype=int32)

In [ ]:
# nancumsum()

In [43]:
x=np.arange(1,10,dtype=float).reshape(3,3)
x


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [45]:
x[1,1]=np.nan

In [46]:
np.nancumsum(x)

array([ 1.,  3.,  6., 10., 10., 16., 23., 31., 40.])

In [47]:
np.nancumprod(x)

array([1.0000e+00, 2.0000e+00, 6.0000e+00, 2.4000e+01, 2.4000e+01,
       1.4400e+02, 1.0080e+03, 8.0640e+03, 7.2576e+04])

In [53]:
# for finding Minimum and Maximum 

In [55]:
x=np.array([1,2,3,4,5])
np.min(x)

1

In [56]:
np.max(x)

5

In [58]:
x1=np.arange(1,10).reshape(3,3)
print(x1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
print(np.min(x1), np.max(x1))


1 9


In [61]:
print(np.min(x1,axis=0), np.min(x1,axis=1))

[1 2 3] [1 4 7]


In [62]:
print(np.max(x1,axis=0), np.max(x1,axis=1))

[7 8 9] [3 6 9]


In [63]:
# inf in sum need to convert the inf value to 0

In [64]:
x1=np.arange(1,10,dtype=float).reshape(3,3)
x1


array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [65]:
x1[0,0]=np.inf
x1

array([[inf,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]])

In [66]:
np.sum(x1)

inf

In [68]:
np.isinf(x1)

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [70]:
x1[np.isinf(x1)]=0

In [71]:
np.sum(x1)

44.0

In [72]:
# Mean

In [74]:
x=np.array([1,2,3,4,5])
np.mean(x)

3.0

In [75]:
x1

array([[0., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [77]:
np.mean(x1)

4.888888888888889

In [78]:
np.mean(x1,axis=0)

array([3.66666667, 5.        , 6.        ])

In [79]:
np.mean(x1,axis=1)

array([1.66666667, 5.        , 8.        ])

In [ ]:
# median

In [80]:
np.median(x)

3.0

In [81]:
x1

array([[0., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [82]:
np.median(x1)

5.0

In [83]:
print(np.median(x1,axis=0),np.median(x1,axis=1))

[4. 5. 6.] [2. 5. 8.]


In [84]:
#how to find the unqiue elements in an n-dim array

In [85]:
x=np.array([1,2,3,4,5,1,1,2,5,6,2,4])
np.unique(x)

array([1, 2, 3, 4, 5, 6])

In [87]:
x1,y1=np.unique(x,return_counts=True)
print(x1,y1)

[1 2 3 4 5 6] [3 3 1 2 2 1]


In [88]:
x1=np.arange(1,10).reshape(3,3)
x1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.unique(x1,return_counts=True,)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [90]:
# transpose --- on 1d

In [4]:
arr1 = np.array([[4, 7], [2, 6]])
Trans_arr = arr1.T         # Transpose of Array (Columans become rows and rows become columns)
print("\nTranspose of Array: ")
print(Trans_arr)


Transpose of Array: 
[[4 2]
 [7 6]]


In [98]:
x1=np.arange(1,10).reshape(9,1)
x1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [99]:
x1.shape

(9, 1)

In [100]:
x1=x1.T
x1

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [101]:
x1.shape

(1, 9)

In [102]:
x1=x1.T
x1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [103]:
# how to flatten your arrays

In [104]:
#flatten() --copy
#ravel()   -- view

In [3]:
a = np.array([[0, 1, 2], [3, 4, 5]])
a.ravel()

array([0, 1, 2, 3, 4, 5])

In [106]:
x1=np.arange(1,10).reshape(3,3)
x1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [107]:
x1.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
x1.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
y=x1.ravel()
print(x1)
print('\n')
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[1 2 3 4 5 6 7 8 9]


In [111]:
y[0]=0
y

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
x1

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
z=x1.flatten()
z

array([0, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
z[0]=100
z

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [115]:
x1

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
#how to repeat the elements n numer of time

In [117]:
x=np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [119]:
print(np.repeat(x,2))
print(np.repeat(x,7))

[1 1 2 2 3 3 4 4]
[1 1 1 1 1 1 1 2 2 2 2 2 2 2 3 3 3 3 3 3 3 4 4 4 4 4 4 4]


In [120]:
x1


array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [121]:
np.repeat(x1,2)

array([0, 0, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [122]:
np.repeat(x1,2)

array([0, 0, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [124]:
y=x1[0,0]
np.repeat(y,2)

array([0, 0])

In [125]:
#how to repeaat the arrays n number of time
x1

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
np.tile(x1,2)

array([[0, 2, 3, 0, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [127]:
np.tile(x1,(1,2))

array([[0, 2, 3, 0, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [128]:
np.tile(x1,(1,3))

array([[0, 2, 3, 0, 2, 3, 0, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [129]:
np.tile(x1,(2,1))

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
np.tile(x1,(3,1))

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 19 Aug 2022

In [3]:
import numpy as np

In [4]:
x=np.random.randint(1,10,(10,))
x

array([1, 4, 7, 5, 8, 1, 5, 9, 1, 8])

In [5]:
x>3 # since it is a condition it returns you a Boolean Dtype

array([False,  True,  True,  True,  True, False,  True,  True, False,
        True])

In [6]:
x[x>3] #by keeping the mask we can get the values that are greater then 3

array([4, 7, 5, 8, 5, 9, 8])

In [7]:
# By using the masking condition we can get the values that are True, but cant the Index Values So..
# To know the index values of those True Values we need to use the "where()" Function.
# "np.where(condition,True,False)"

In [8]:
# Application of where function on 1d- array

In [9]:
x

array([1, 4, 7, 5, 8, 1, 5, 9, 1, 8])

In [15]:
m=x[x>3]
m

array([4, 7, 5, 8, 5, 9, 8])

In [16]:
np.where(x[x>3]) # the values that are going to return are Index Values of the Given Arrary

(array([0, 1, 2, 3, 4, 5, 6], dtype=int64),)

In [17]:
# to get back your indexing values to the True values use "take()""
#take function is only applicable on 1dim.

In [18]:
n=x.take(np.where(x[x>3]))
n

array([[1, 4, 7, 5, 8, 1, 5]])

In [19]:
m==n

array([[False, False, False, False, False, False, False]])

In [20]:
# Application of where function on 2d- array

In [43]:
x1=np.random.randint(1,10,(4,5))
x1

array([[7, 5, 5, 6, 3],
       [9, 4, 6, 9, 9],
       [1, 1, 1, 5, 6],
       [2, 4, 8, 4, 9]])

In [44]:
x1[x1>3]

array([7, 5, 5, 6, 9, 4, 6, 9, 9, 5, 6, 4, 8, 4, 9])

In [45]:
np.where(x1>3)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 4, 3, 4, 1, 2, 3, 4], dtype=int64))

In [ ]:
''' this the indiexing values of the True condition in [rows][colunm]
[0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 3, 3, 3]
[0, 1, 2, 3, 0, 1, 2, 3, 4, 3, 4, 1, 2, 3, 4]'''

In [46]:
# take will not work on 2dim arrays /***\

In [49]:
x2=np.arange(59,69).reshape(10,)
x2

array([59, 60, 61, 62, 63, 64, 65, 66, 67, 68])

In [ ]:
# np.where(condition,True,False)

In [51]:
np.where(x%3==0,'divisible','notdivisible')

array(['notdivisible', 'divisible', 'notdivisible', 'notdivisible',
       'divisible', 'notdivisible', 'notdivisible', 'divisible',
       'notdivisible', 'notdivisible'], dtype='<U12')

In [53]:
x3=np.arange(59,68).reshape(3,3)
x3

array([[59, 60, 61],
       [62, 63, 64],
       [65, 66, 67]])

In [55]:
np.where(x%3==0,'divi','notdivi')

array(['notdivi', 'divi', 'notdivi', 'notdivi', 'divi', 'notdivi',
       'notdivi', 'divi', 'notdivi', 'notdivi'], dtype='<U7')

In [ ]:
# to know the index value we can use 'arg()'. np.arg()

In [68]:
x6=np.random.randint(1,10,(10,))
x6

array([8, 8, 4, 4, 9, 3, 8, 5, 6, 6])

In [69]:
np.argmin(x6) # it will return you a index value of the min valu in given array

5

In [70]:
np.argmax(x6) # it will return you a index value of the maxi valu in given array

4

In [72]:
# argwhere()  also retuns you index vales as where "np.argwhere(condition)"

In [84]:
x7= np.arange(6).reshape(2,3)
x7


array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
np.argwhere(x7>1)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]], dtype=int64)

In [87]:
np.where(x7>1)

(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [ ]:
# Combining two or more arrays into a single array using concatenate()
#np.concatenate([array1,array2])


In [56]:
x4=np.random.randint(61,69,(3,3))
x5=np.random.randint(51,59,(3,3))
x4


array([[62, 62, 62],
       [67, 64, 64],
       [67, 65, 66]])

In [57]:
x5

array([[53, 54, 52],
       [57, 57, 53],
       [58, 51, 52]])

In [58]:
np.concatenate([x4,x5]) # default it arranges row wise (one below the other)

array([[62, 62, 62],
       [67, 64, 64],
       [67, 65, 66],
       [53, 54, 52],
       [57, 57, 53],
       [58, 51, 52]])

In [59]:
np.concatenate([x4,x5],axis=0) # it arrang the 2nd array below to first arry

array([[62, 62, 62],
       [67, 64, 64],
       [67, 65, 66],
       [53, 54, 52],
       [57, 57, 53],
       [58, 51, 52]])

In [60]:
np.concatenate([x4,x5],axis=1) # it arrang the 2nd array next side to first arry

array([[62, 62, 62, 53, 54, 52],
       [67, 64, 64, 57, 57, 53],
       [67, 65, 66, 58, 51, 52]])

In [61]:
# 'hstack()' and 'Vstack()' functions

In [ ]:
# 'hstack()' and 'Vstack() are similar to concatenate function Thet donot use axis
# np.hstack() concatenate horizontally(beside) and np.vstack() concatinate vertically(down`)

In [62]:
x4

array([[62, 62, 62],
       [67, 64, 64],
       [67, 65, 66]])

In [63]:
x5

array([[53, 54, 52],
       [57, 57, 53],
       [58, 51, 52]])

In [65]:
np.hstack([x4,x5])

array([[62, 62, 62, 53, 54, 52],
       [67, 64, 64, 57, 57, 53],
       [67, 65, 66, 58, 51, 52]])

In [66]:
np.vstack([x4,x5])

array([[62, 62, 62],
       [67, 64, 64],
       [67, 65, 66],
       [53, 54, 52],
       [57, 57, 53],
       [58, 51, 52]])

In [88]:
# Logical Operators "and" and 'or' # returns a boolen data

In [90]:
x8=np.array([1,2,3,4])
x9=np.array([11,22,33,44])
np.logical_and(x8,x9)

array([ True,  True,  True,  True])

In [ ]:
#hear comparision is done on elementwise and returns true if both the condition are true else False

In [93]:
x10=np.array([0,22,33,44])
np.logical_and(x9,x10)

array([False,  True,  True,  True])

In [94]:
x8=np.array([1,2,3,4])
x9=np.array([11,22,33,44])
np.logical_or(x8,x9)

array([ True,  True,  True,  True])

In [ ]:
#hear comparision is done on elementwise and returns true if any of the condition are true 

In [95]:
x10=np.array([0,22,33,44])
np.logical_or(x9,x10)

array([ True,  True,  True,  True])

In [96]:
#np.all() and np.any() 

In [97]:
# np.all -> will work on single arraay and retun true if all elements in the array are true

In [98]:
# np.any() -> will work on single arraay and retun true if any one elements in the array is true

In [100]:
y1=np.arange(0,20,2).reshape(10,)
y1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [101]:
y1%2==0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [103]:
np.all(y1%2==0)

True

In [105]:
np.all((y1%2==0) & (y1%3==0))

False

In [106]:
np.any(y1%2==0)

True

In [107]:
np.any((y1%2==0) & (y1%3==0))

True

In [108]:
# how to sort a array 

In [111]:
y2=np.random.randint(1,10,(10,))
y2

array([8, 8, 6, 3, 6, 5, 3, 5, 8, 8])

In [112]:
np.sort(y2)

array([3, 3, 5, 5, 6, 6, 8, 8, 8, 8])

In [114]:
k=np.sort(y2)
k[::-1]


array([8, 8, 8, 8, 6, 6, 5, 5, 3, 3])

In [117]:
y3=np.random.randint(1,30,(6,6))
y3

array([[25,  2,  5,  1, 20, 14],
       [ 3, 23, 17, 29, 29, 19],
       [17, 14, 25,  5, 11, 11],
       [ 4, 25, 24, 17, 25, 12],
       [24, 11,  1,  8,  4, 23],
       [ 5, 22, 23, 24, 23,  5]])

In [122]:
a=np.sort(y3)  #by default it will sort row only not column wise.
a

array([[ 1,  2,  5, 14, 20, 25],
       [ 3, 17, 19, 23, 29, 29],
       [ 5, 11, 11, 14, 17, 25],
       [ 4, 12, 17, 24, 25, 25],
       [ 1,  4,  8, 11, 23, 24],
       [ 5,  5, 22, 23, 23, 24]])

In [123]:
np.sort(a,axis=0)

array([[ 1,  2,  5, 11, 17, 24],
       [ 1,  4,  8, 14, 20, 24],
       [ 3,  5, 11, 14, 23, 25],
       [ 4, 11, 17, 23, 23, 25],
       [ 5, 12, 19, 23, 25, 25],
       [ 5, 17, 22, 24, 29, 29]])

In [124]:
y4=np.array([9,6,7,3,6,1,4,5])
np.argsort(y4)   # it returns the indexing valus of the output.

array([5, 3, 6, 7, 1, 4, 2, 0], dtype=int64)

In [125]:
# Converting the Data Type 

In [126]:
# To Convert the Data Type we use 'astype()' function

In [127]:
y5=np.array([9,6,7,3,6,1,4,5])

In [133]:
print(y5.dtype)

int32


In [163]:
y5.astype(float)

array([9., 6., 7., 3., 6., 1., 4., 5.])

In [164]:
# Copy and View 

In [167]:
c=np.random.randint(1,10,(3,3))
c

array([[1, 6, 3],
       [1, 7, 7],
       [5, 9, 7]])

In [168]:
x=c[1:,1:]
x

array([[7, 7],
       [9, 7]])

In [170]:
x[0,0]=100
x

array([[100,   7],
       [  9,   7]])

In [179]:
c=np.random.randint(1,10,(3,3))
c

array([[9, 7, 4],
       [8, 1, 9],
       [5, 1, 7]])

In [173]:
x=c[1:,1:].view()   # in view if you change the sub array the the orginal array will also changes
x

array([[100,   7],
       [  9,   7]])

In [175]:
x[0,0]=10000
x

array([[10000,     7],
       [    9,     7]])

In [176]:
c

array([[    1,     6,     3],
       [    1, 10000,     7],
       [    5,     9,     7]])

In [177]:
#copy

In [178]:
c=np.random.randint(1,10,(3,3))


In [180]:
x=c[1:,1:].copy() # in copy if you change the sub array the the orginal array will not effected
x

array([[1, 9],
       [1, 7]])

In [181]:
x[0,0]=10000
x

array([[10000,     9],
       [    1,     7]])

In [182]:
c

array([[9, 7, 4],
       [8, 1, 9],
       [5, 1, 7]])

In [1]:
# python broadcasting (hear if both the arrays are not equal then the they makes same dummy valus)

In [ ]:
# Example 1

In [5]:
x=np.arange(3)
x

array([0, 1, 2])

In [6]:
x+5

array([5, 6, 7])

In [ ]:
# Example 2

In [7]:
np.ones((3,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.ones((3,3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
# Example 3

In [10]:
np.arange(3).reshape((3,1))

array([[0],
       [1],
       [2]])

In [12]:
np.arange(3)

array([0, 1, 2])

In [11]:
np.arange(3).reshape((3,1))+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
# np.nonzero() --> returns the index values of nonzero elements.

In [16]:
import numpy as geek
arr = geek.array([[0, 8, 0], [7, 0, 0], [-5, 0, 1]])
print(arr) 
nonzero= geek.nonzero(arr)
print ("Indices of non zero elements : ",nonzero) 


[[ 0  8  0]
 [ 7  0  0]
 [-5  0  1]]
Indices of non zero elements :  (array([0, 1, 2, 2], dtype=int64), array([1, 0, 0, 2], dtype=int64))


In [17]:
# How to save the array

In [ ]:
# for saving the single array use .npy and use 'np.save'

In [23]:
y=np.array((0,10))
    np.save("C:\\Users\\Gogula Vinay\\Desktop\\Innomatics labs\\Data Science\\Numpy class notes\\arr1.npy",y)

In [ ]:
# for saving the single array use .npz and use 'np.savez'

In [30]:
z=np.array((0,13))
np.savez("C:\\Users\\Gogula Vinay\\Desktop\\Innomatics labs\\Data Science\\Numpy class notes\\arr2.npz",y,z)

In [ ]:
# to get the values 'load the array' k=np.load('give path hear') and k.files.

In [ ]:
# Difference Between Python List and Numpy array

In [2]:
x=np.array([1,2,3])

In [3]:
y=[1,2,3]

In [4]:
type(x)

numpy.ndarray

In [5]:
type(y)

list

In [6]:
x

array([1, 2, 3])

In [7]:
x+2

array([3, 4, 5])

In [8]:
y+2

TypeError: can only concatenate list (not "int") to list

In [10]:
x*3

array([3, 6, 9])

In [11]:
y*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [12]:
x

array([1, 2, 3])

In [13]:
x[3]=1000

IndexError: index 3 is out of bounds for axis 0 with size 3

In [14]:
y

[1, 2, 3]

In [16]:
y.append(4)
y

[1, 2, 3, 4, 4]

In [17]:
import time
x=time.time()
np.arange(0,10000000)
y=time.time()
print(y-x)

0.03889870643615723


In [18]:
x=time.time()
l=[]
for y in range(0,10000000):
    l.append(y)
y=time.time()
print(y-x)

2.351081132888794


In [ ]:
# Ceil()
'''Return the ceiling of the input, element-wise.

The ceil of the scalar x is the smallest integer i, 
such that i >= x. It is often denoted as .'''

In [2]:
import numpy  as np 
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.ceil(a)

array([-1., -1., -0.,  1.,  2.,  2.,  2.])

In [ ]:
# trunc ()
'''Return the truncated value of the input, element-wise.

The truncated value of the scalar x is the nearest integer i which is closer to zero than x is. 
In short, the fractional part of the signed number x is discarded.'''

In [3]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.trunc(a)

array([-1., -1., -0.,  0.,  1.,  1.,  2.])

In [ ]:
# floor()
'''Return the floor of the input, element-wise.

The floor of the scalar x is the largest integer i, 
such that i <= x. It is often denoted as .'''

In [4]:
a = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])
np.floor(a)

array([-2., -2., -1.,  0.,  1.,  1.,  2.])

In [5]:
# round()


In [6]:
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1]
np.round_(in_array)

array([ 0.,  2.,  2.,  4.,  4., 10.])

In [9]:
in_array = [.5538, 1.33354, .71445]
np.round_(in_array, decimals = 3)

array([0.554, 1.334, 0.714])

In [17]:
# Date and time


In [18]:
import datetime
today=datetime.datetime.today()
print('Todays Date: ',today)
yesterday=today-datetime.timedelta(days=1)
print('Yesterday: ',yesterday)
tomorrow=today+datetime.timedelta(days=1)
print('Tomorrow: ',tomorrow)

Todays Date:  2022-09-10 12:48:24.128854
Yesterday:  2022-09-09 12:48:24.128854
Tomorrow:  2022-09-11 12:48:24.128854


In [19]:
print("First Monday in May 2017:")
print(np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon'))


First Monday in May 2017:
2017-05-01


In [1]:
import numpy as np

In [2]:
arr=np.array([[40,50,60,70,80],[45,55,65,75,85]])
np.where(arr>64,arr/10,arr)

array([[40. , 50. , 60. ,  7. ,  8. ],
       [45. , 55. ,  6.5,  7.5,  8.5]])

In [7]:
x=20
y=30
if((x+1)>20 | y+1>30):
    print('inside if',end='')
else:
    print('jhbag')

jhbag
